apiVersion: apps/v1
kind: Service 
metadata:
  name: devops
spec:
  selector:
       app: devops
  
  ports:
      -protocol = "TCP"
      port= 8080
      targetport: 8080
            
  type = NodePort
