apiVersion: apps/v1
kind: Deployment 
metadata:
  name: devops
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 3
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name:devops
          image: devops:1.0 
          
          ports:
            - containerPort: 8080
